name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: csharp, javascript, typescript  # Specify the languages used in your project

      - name: Build and analyze CodeQL database
        uses: github/codeql-action/autobuild@v1
