name: Bearer

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bearer/bearer-action@v2
